--------------------------------------------------------------
 --     Copyright (c) 2012-2024 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/School_Files/FPGA/SparkRoad_Gesture_Recognition/al_ip/g0_rom.vhd
 -- Date	:	2024 11 23
 -- TD version	:	5.6.119222
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY g0_rom IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(23 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(13 DOWNTO 0);
	ocea		: IN STD_LOGIC;
	rsta		: IN STD_LOGIC;
	clka		: IN STD_LOGIC
	);
END g0_rom;

ARCHITECTURE struct OF g0_rom IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 24,
			ADDR_WIDTH_A	=> 14,
			DATA_DEPTH_A	=> 10000,
			DATA_WIDTH_B	=> 24,
			ADDR_WIDTH_B	=> 14,
			DATA_DEPTH_B	=> 10000,
			MODE			=> "SP",
			REGMODE_A	=> "OUTREG",
			IMPLEMENT	=> "32K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "mif/g0.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> rsta,
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea	=> ocea,
			oceb		=> '0'
		);

END struct;
