/************************************************************\
 **     Copyright (c) 2012-2024 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/School_Files/FPGA/SparkRoad_Gesture_Recognition/al_ip/g1_rom.v
 ** Date	:	2024 11 23
 ** TD version	:	5.6.119222
\************************************************************/

`timescale 1ns / 1ps

module g1_rom ( doa, addra, ocea, clka, rsta );

	output [23:0] doa;

	input  [13:0] addra;
	input  ocea;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(24),
				.ADDR_WIDTH_A(14),
				.DATA_DEPTH_A(10000),
				.DATA_WIDTH_B(24),
				.ADDR_WIDTH_B(14),
				.DATA_DEPTH_B(10000),
				.MODE("SP"),
				.REGMODE_A("OUTREG"),
				.IMPLEMENT("32K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("mif/g1.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({24{1'b0}}),
				.dib({24{1'b0}}),
				.addra(addra),
				.addrb({14{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(ocea),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule